/*
 * Scale.h
 *
 *  Created on: Nov 12, 2016
 *      Author: User
 */

#ifndef Y_ENGINE_COMPONENTS_SIMULATION_UTILITIES_TRANSFORM_SCALE_SCALE_H_
#define Y_ENGINE_COMPONENTS_SIMULATION_UTILITIES_TRANSFORM_SCALE_SCALE_H_





#endif /* Y_ENGINE_COMPONENTS_SIMULATION_UTILITIES_TRANSFORM_SCALE_SCALE_H_ */
